export const formSelectors = {

    user: {
        class: 'user',
        id: 'user-id',
        idClass: 'user-id',
        userId: 'username',
        passId: 'password',
        newPassId: 'new-password',
        confPassId: 'confirm-password',
        tokenId: 'auth-token',
        firstNameId: 'user-first-name',
        lastNameId: 'user-last-name',
        aliasId: 'user-alias',
        nameClass: 'user-name',
        genderId: 'user-gender',
        genderClass: 'user-gender',
        emailId: 'user-email',
        phoneId: 'user-phone',
        conditionId: 'user-condition',
        conditionClass: 'user-condition',
        statusId: 'user-status',
        locationId: 'user-location',
        loginFormId: 'login-form',
        registerFormId: 'register-form',
        authFormId: 'auth-form',
        mainFormId: 'user-form',
        deleteFormId: 'user-delete-form',
        conditionFormId: 'user-condition-form',
        profileFormId: 'user-profile-form',
        accountFormId: 'user-account-form',
        securityFormId: 'user-security-form',
        signInButtonId: 'sign-in',
        signUpButtonId: 'sign-up',
        signOutLinkId: 'sign-out',
        authButtonId: 'authenticate',
        roleId: 'user-role-id',
        roleNameId: 'user-role-name',
        roleLocationId: 'user-role-location',
        carrierRoleId: 'user-carrier-role-id',
        carrierRoleNameId: 'user-carrier-role-name',
        carrierRoleLocationId: 'user-carrier-role-location',
    },

    company: {
        id: 'company-id',
        catId: 'company-category',
        sinceId: 'company-since',
        einId: 'company-ein',
        dunsId: 'company-duns',
        busNameId: 'company-busname',
        coTypeId: 'company-cotype',
        aliasId: 'company-alias',
        websiteId: 'company-website',
        ownershipId: 'company-ownership',
        addr1Id: 'company-address1',
        addr2Id: 'company-address2',
        zipId: 'compnay-zip',
        cityId: 'company-city',
        stateId: 'company-state',
        mailStatusId: 'company-mail-address',
        mailAddr1Id: 'company-mail-addr1',
        mailAddr2Id: 'company-mail-addr2',
        mailZipId: 'company-mail-zip',
        mailCityId: 'company-mail-city',
        mailStateId: 'company-mail-state',
        phoneId: 'company-phone',
        faxId: 'company-fax',
        emailId: 'company-email',
    },

    owner: {
        class: 'company-owner',
        id: 'company-owner-id',
        deleteOwnerId: 'company-owner-delete-id',
        ownerPhoneId: 'company-owner-delete-id',
        updateSinceId: 'company-owner-update-since',
        prefixId: 'company-owner-pfx',
        firstNameId: 'company-owner-fname',
        middleNameId: 'company-owner-mname',
        lastNameId: 'company-owner-lname',
        suffixId: 'company-owner-sfx',
        genderId: 'company-owner-gender',
        genderClass: 'company-owner-gender',
        dobId: 'company-owner-dob',
        ssnId: 'company-owner-ssn',
        phoneId: 'company-owner-phone',
    },

    team: {
        class: 'team',
        id: 'team-id',
        catId: 'team-category',
        nameId: 'team-name',
        descId: 'team-description',
    },

    carrier: {
        mcId: 'carrier-mc',
        usdotId: 'carrier-usdot',
        scacId: 'carrier-scac',
        iftaId: 'carrier-ifta',
        iftaJurId: 'carrier-ifta-jurisdiction',
        irpId: 'carrier-irp',
        permit: target => `carrier-${target}-permit`,
        efsId: 'carrier-efs',
        fleetOneId: 'carrier-fleet-one',
        transfloId: 'carrier-transflo',
    },

    driver: {
        class: 'driver',
        id: 'driver-id',
        aplId: 'driver-apl-id',
        aplFormId: 'driver-apl-from-id',
        prefixId: 'driver-pfx',
        firstNameId: 'driver-fname',
        middleNameId: 'driver-mname',
        lastNameId: 'driver-lname',
        suffixId: 'driver-sfx',
        dobId: 'driver-dob',
        ssnId: 'driver-ssn',
        phoneId: 'driver-phone',
        emailId: 'driver-email',
        positionId: 'driver-position',
        statusExpId: 'driver-status-expires',
    },

}